import type { NextPage } from 'next';
import Head from 'next/head';
// import Navbar from '../components/Navbar';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
  const router = useRouter();

  return (
    <div className="w-screen">
      <Head>
        <title>Template</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen "></main>

      {/* <footer className="bg-black">sss</footer> */}
    </div>
  );
};

export default Home;
